# Generated by Django 4.1.5 on 2023-01-21 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='User',
            new_name='usuario',
        ),
    ]
